-- =============================================================================
-- Stock SDI Demo — PostgreSQL Homelab — migration 001 setup
-- 1) Buat role  : stock_sdi_demo_user (LOGIN, bukan superuser)
-- 2) Buat database : stock_sdi_demo (owner = role aplikasi)
-- 3) Skema/structure lengkap (tanpa auth.users & RLS)
-- Target eksekusi: sudo -u postgres psql --set ON_ERROR_STOP=1 -f <file>
-- Password role DIBACA dari /tmp/stock_sdi_pw (dibuat terpisah, chmod 644)
-- dan TIDAK muncul di repo / output / cmdline.
-- Guard: jika role ATAU database sudah ada -> RAISE EXCEPTION -> abort
-- (psql -v ON_ERROR_STOP=1). Tidak ada drop/reset apa pun.
-- =============================================================================

\set dbpw `cat /tmp/stock_sdi_pw`

-- -----------------------------------------------------------------------------
-- Guard: pastikan belum ada role/database target
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'stock_sdi_demo_user') THEN
    RAISE EXCEPTION 'role stock_sdi_demo_user already exists; aborting setup';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_database WHERE datname = 'stock_sdi_demo') THEN
    RAISE EXCEPTION 'database stock_sdi_demo already exists; aborting setup';
  END IF;
END
$$;

-- -----------------------------------------------------------------------------
-- Role & database (wajib di luar BEGIN/COMMIT: CREATE DATABASE non-transaksi)
-- -----------------------------------------------------------------------------
CREATE ROLE stock_sdi_demo_user LOGIN PASSWORD :'dbpw';

CREATE DATABASE stock_sdi_demo
  WITH OWNER stock_sdi_demo_user;

\c stock_sdi_demo

-- Semua objek di bawah di-OWN oleh role aplikasi (bukan postgres)
SET ROLE stock_sdi_demo_user;

-- =============================================================================
BEGIN;

-- -----------------------------------------------------------------------------
-- Tabel: profiles (tanpa FK ke auth.users -- desain auth custom nanti)
-- -----------------------------------------------------------------------------
-- PERUBAHAN vs Supabase:
--   Supabase : id uuid PK REFERENCES auth.users(id) ON DELETE CASCADE,
--              diisi trigger on_auth_user_created (handle_new_user)
--   Homelab  : id uuid PK (no FK), baris diisi oleh Node.js auth (tahap berikut).
--              role CHECK dipertahankan (staff | guest).
CREATE TABLE public.profiles (
    id uuid NOT NULL,
    nama text NOT NULL,
    role text NOT NULL DEFAULT 'staff'::text,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_role_check CHECK (role = ANY (ARRAY['staff'::text, 'guest'::text]))
);

-- -----------------------------------------------------------------------------
-- Tabel: barang
-- -----------------------------------------------------------------------------
CREATE TABLE public.barang (
    id bigint GENERATED ALWAYS AS IDENTITY,
    nama text NOT NULL,
    stok integer NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT barang_pkey PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- Tabel: stock_levels
-- -----------------------------------------------------------------------------
CREATE TABLE public.stock_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    item_id bigint NOT NULL,
    warehouse text NOT NULL,
    kriteria text NOT NULL,
    jumlah numeric NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT stock_levels_pkey PRIMARY KEY (id),
    CONSTRAINT stock_levels_item_id_warehouse_kriteria_key UNIQUE (item_id, warehouse, kriteria),
    CONSTRAINT stock_levels_item_id_fkey FOREIGN KEY (item_id)
        REFERENCES public.barang (id) ON DELETE CASCADE,
    CONSTRAINT stock_levels_kriteria_check CHECK (kriteria = ANY (ARRAY['Good'::text, 'Bad'::text])),
    CONSTRAINT stock_levels_warehouse_check CHECK (warehouse = ANY (ARRAY['Puri'::text, 'CS TCL'::text, 'CS SBF'::text]))
);

-- -----------------------------------------------------------------------------
-- Tabel: transaksi
-- -----------------------------------------------------------------------------
-- PERUBAHAN vs Supabase:
--   Supabase : user_id uuid DEFAULT auth.uid() REFERENCES auth.users(id)
--   Homelab  : user_id uuid NULL, TANPA default dan TANPA FK ke auth.users.
--              API auth custom akan mengisinya di tahap berikutnya.
CREATE TABLE public.transaksi (
    id bigint GENERATED ALWAYS AS IDENTITY,
    barang_id bigint NOT NULL,
    jenis text NOT NULL,
    jumlah integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    keterangan text,
    warehouse text NOT NULL DEFAULT 'Puri'::text,
    kriteria text NOT NULL DEFAULT 'Good'::text,
    user_id uuid,
    client_tx_id uuid,
    CONSTRAINT transaksi_pkey PRIMARY KEY (id),
    CONSTRAINT transaksi_barang_id_fkey FOREIGN KEY (barang_id)
        REFERENCES public.barang (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT transaksi_jenis_check CHECK (jenis = ANY (ARRAY['masuk'::text, 'keluar'::text])),
    CONSTRAINT transaksi_jumlah_check CHECK (jumlah > 0),
    CONSTRAINT transaksi_kriteria_check CHECK (kriteria = ANY (ARRAY['Good'::text, 'Bad'::text])),
    CONSTRAINT transaksi_warehouse_check CHECK (warehouse = ANY (ARRAY['Puri'::text, 'CS TCL'::text, 'CS SBF'::text]))
);

-- -----------------------------------------------------------------------------
-- INDEXES  (dari indexes.sql snapshot)
-- -----------------------------------------------------------------------------
CREATE INDEX idx_stock_levels_item ON public.stock_levels USING btree (item_id);
CREATE INDEX transaksi_created_at_id_idx ON public.transaksi USING btree (created_at DESC, id DESC);
CREATE INDEX transaksi_barang_created_id_idx ON public.transaksi USING btree (barang_id, created_at DESC, id DESC);
CREATE UNIQUE INDEX transaksi_client_tx_id_key ON public.transaksi USING btree (client_tx_id) WHERE (client_tx_id IS NOT NULL);

-- -----------------------------------------------------------------------------
-- FUNCTIONS  (body DIAMBIL dari snapshot/functions.sql, bukan ditulis ulang)
-- -----------------------------------------------------------------------------

-- 1. seed_stock_levels_barang  (AFTER INSERT ON barang)
CREATE OR REPLACE FUNCTION public.seed_stock_levels_barang()
 RETURNS trigger
 LANGUAGE plpgsql
 VOLATILE
AS $function$
BEGIN
  IF COALESCE(new.stok, 0) <> 0 THEN
    INSERT INTO stock_levels (item_id, warehouse, kriteria, jumlah)
    VALUES (new.id, 'Puri', 'Good', new.stok)
    ON CONFLICT (item_id, warehouse, kriteria)
    DO UPDATE SET jumlah = excluded.jumlah, updated_at = now();
  END IF;
  RETURN new;
END;
$function$;

-- 2. sync_saldo_transaksi  (AFTER INSERT ON transaksi)
CREATE OR REPLACE FUNCTION public.sync_saldo_transaksi()
 RETURNS trigger
 LANGUAGE plpgsql
 VOLATILE
AS $function$
DECLARE
  cur numeric;
  delta numeric;
BEGIN
  IF new.jenis = 'masuk' THEN
    delta := new.jumlah;
  ELSE
    delta := -new.jumlah;
  END IF;

  -- Cegah stok warehouse+kriteria jadi negatif
  SELECT COALESCE(SUM(jumlah), 0) INTO cur
  FROM stock_levels
  WHERE item_id = new.barang_id AND warehouse = new.warehouse AND kriteria = new.kriteria;
  IF new.jenis = 'keluar' AND cur < new.jumlah THEN
    RAISE EXCEPTION 'Stok tidak mencukupi untuk % di % (%)', new.barang_id, new.warehouse, new.kriteria
      USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO stock_levels (item_id, warehouse, kriteria, jumlah)
  VALUES (new.barang_id, new.warehouse, new.kriteria, delta)
  ON CONFLICT (item_id, warehouse, kriteria)
  DO UPDATE SET jumlah = stock_levels.jumlah + delta, updated_at = now();

  -- Sinkron total di tabel barang
  UPDATE barang SET stok = COALESCE((SELECT SUM(jumlah) FROM stock_levels WHERE item_id = new.barang_id), 0)
  WHERE id = new.barang_id;

  RETURN new;
END;
$function$;

-- 3. riwayat_balance_before  (RPC read-only STABLE -- export riwayat)
CREATE OR REPLACE FUNCTION public.riwayat_balance_before(p_barang_id bigint, p_created_at timestamp with time zone, p_id bigint)
 RETURNS numeric
 LANGUAGE sql
 STABLE
AS $function$
  SELECT COALESCE(
    SUM(
      CASE
        WHEN t.jenis = 'masuk' THEN t.jumlah
        WHEN t.jenis = 'keluar' THEN -t.jumlah
        ELSE 0
      END
    ),
    0
  )::numeric
  FROM public.transaksi t
  WHERE t.barang_id = p_barang_id
    AND (
      t.created_at < p_created_at
      OR (
        t.created_at = p_created_at
        AND t.id < p_id
      )
    );
$function$;

-- 4. update_stok_barang  -- DEAD CODE di Supabase (tidak dipasang trigger).
--    DIBUAT agar kompatibel dengan dump referensi, TAPI TIDAK diaktifkan ke
--    trigger mana pun. API tidak boleh memanggilnya.
CREATE OR REPLACE FUNCTION public.update_stok_barang()
 RETURNS trigger
 LANGUAGE plpgsql
 VOLATILE
AS $function$
BEGIN
  IF new.jenis = 'masuk' THEN
    UPDATE barang SET stok = stok + new.jumlah, updated_at = now() WHERE id = new.barang_id;
  ELSE
    UPDATE barang SET stok = stok - new.jumlah, updated_at = now() WHERE id = new.barang_id;
  END IF;
  RETURN new;
END;
$function$;

-- -----------------------------------------------------------------------------
-- CATATAN: handle_new_user TIDAK dibuat -- bergantung auth.users / auth.uid().
--          Akan dimigrasikan bersama desain authentication (tahap berikut).
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- TRIGGERS  (dari triggers.sql snapshot)
-- -----------------------------------------------------------------------------
CREATE TRIGGER trg_barang_seed_saldo
    AFTER INSERT ON public.barang
    FOR EACH ROW
    EXECUTE FUNCTION public.seed_stock_levels_barang();

CREATE TRIGGER trg_transaksi_sync_saldo
    AFTER INSERT ON public.transaksi
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_saldo_transaksi();

-- -----------------------------------------------------------------------------
-- IDENTITY / SEQUENCE
-- Kolom identity dibuat oleh definisi GENERATED ... IDENTITY di atas.
-- Nilai next diset di migration 004 (setelah seed + test), sesuai snapshot:
--   barang next = 37, stock_levels next = 64, transaksi next = 59.
-- -----------------------------------------------------------------------------

COMMIT;
-- =============================================================================