-- =============================================================================
-- Full DDL snapshot — public schema
-- Project : Stock SDI Demo (supabase: stock-sdi / rwbplixadhmuytkymwcb)
-- Source  : Direkonstruksi dari system catalog (pg_get_constraintdef /
--           pg_get_indexdef / pg_get_functiondef / pg_get_triggerdef)
--           via Management API SQL endpoint (read-only). BUKAN hasil pg_dump.
-- Server  : PostgreSQL 17.6, database "postgres", encoding UTF8,
--           collate/ctype en_US.UTF-8, TimeZone UTC.
-- Note    : File ini berisi DDL untuk schema public. Objek yang bergantung
--           pada Supabase Auth ditandai dengan komentar [SUPABASE-AUTH] dan
--           TIDAK boleh langsung dijalankan di PostgreSQL homelab tanpa
--           menyesuaikan skema auth.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabel: public.barang
-- -----------------------------------------------------------------------------
CREATE TABLE public.barang (
    id bigint GENERATED ALWAYS AS IDENTITY,
    nama text NOT NULL,
    stok integer NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT barang_pkey PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- Tabel: public.profiles
-- -----------------------------------------------------------------------------
-- [SUPABASE-AUTH] kolom id = FK ke auth.users(id) (ON DELETE CASCADE).
-- Ditulis otomatis oleh trigger on_auth_user_created saat user Auth dibuat.
CREATE TABLE public.profiles (
    id uuid NOT NULL,
    nama text NOT NULL,
    role text NOT NULL DEFAULT 'staff'::text,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT profiles_role_check CHECK (role = ANY (ARRAY['staff'::text, 'guest'::text]))
);

-- -----------------------------------------------------------------------------
-- Tabel: public.stock_levels
-- -----------------------------------------------------------------------------
CREATE TABLE public.stock_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    item_id bigint NOT NULL,
    warehouse text NOT NULL,
    kriteria text NOT NULL,
    jumlah numeric NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT stock_levels_pkey PRIMARY KEY (id),
    CONSTRAINT stock_levels_item_id_warehouse_kriteria_key UNIQUE (item_id, warehouse, kriteria),
    CONSTRAINT stock_levels_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.barang(id) ON DELETE CASCADE,
    CONSTRAINT stock_levels_kriteria_check CHECK (kriteria = ANY (ARRAY['Good'::text, 'Bad'::text])),
    CONSTRAINT stock_levels_warehouse_check CHECK (warehouse = ANY (ARRAY['Puri'::text, 'CS TCL'::text, 'CS SBF'::text]))
);

-- -----------------------------------------------------------------------------
-- Tabel: public.transaksi
-- -----------------------------------------------------------------------------
-- [SUPABASE-AUTH] kolom user_id = FK ke auth.users(id) (tanpa cascade),
-- default auth.uid().
CREATE TABLE public.transaksi (
    id bigint GENERATED ALWAYS AS IDENTITY,
    barang_id bigint NOT NULL,
    jenis text NOT NULL,
    jumlah integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    keterangan text,
    warehouse text NOT NULL DEFAULT 'Puri'::text,
    kriteria text NOT NULL DEFAULT 'Good'::text,
    user_id uuid DEFAULT auth.uid(),
    client_tx_id uuid,
    CONSTRAINT transaksi_pkey PRIMARY KEY (id),
    CONSTRAINT transaksi_barang_id_fkey FOREIGN KEY (barang_id) REFERENCES public.barang(id),
    CONSTRAINT transaksi_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
    CONSTRAINT transaksi_jenis_check CHECK (jenis = ANY (ARRAY['masuk'::text, 'keluar'::text])),
    CONSTRAINT transaksi_jumlah_check CHECK (jumlah > 0),
    CONSTRAINT transaksi_kriteria_check CHECK (kriteria = ANY (ARRAY['Good'::text, 'Bad'::text])),
    CONSTRAINT transaksi_warehouse_check CHECK (warehouse = ANY (ARRAY['Puri'::text, 'CS TCL'::text, 'CS SBF'::text]))
);

-- -----------------------------------------------------------------------------
-- Tabel: public.user_sessions
-- -----------------------------------------------------------------------------
-- [SUPABASE-AUTH] user_id = FK ke auth.users(id) (ON DELETE CASCADE).
-- Tidak direferensikan oleh frontend aplikasi (kemungkinan legacy).
CREATE TABLE public.user_sessions (
    user_id uuid NOT NULL,
    session_token uuid NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_sessions_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Sequences / Identity (info konfigurasi dari pg_sequence)
-- Nilai awal semua: 1, increment: 1, min: 1, max: 9223372036854775807,
-- cycle: OFF, tipe bigint, owner = postgres.
-- Catatan: kolom identity dibuat otomatis oleh definisi GENERATED ... IDENTITY
-- di atas, sehingga DDL ini dibuat untuk dokumentasi saja. Nilai last_value
-- adalah snapshot saat query dijalankan (data-derived, TIDAK di-embed ke
-- definisi; perlu diset ulang saat migrasi mempertahankan ID lanjutan).
--
--   public.barang_id_seq         owned by public.barang.id     last_value = 36
--   public.stock_levels_id_seq   owned by public.stock_levels.id  last_value = 63
--   public.transaksi_id_seq      owned by public.transaksi.id   last_value = 58
--
-- Apabila homelab harus meneruskan ID yang sama, jalankan setelah CREATE TABLE:
--   ALTER TABLE public.barang ALTER COLUMN id RESTART WITH 37;
--   ALTER TABLE public.stock_levels ALTER COLUMN id RESTART WITH 64;
--   ALTER TABLE public.transaksi ALTER COLUMN id RESTART WITH 59;
-- (nilai = last_value + 1). Hanya lakukan bila data juga dimigrasikan.
-- =============================================================================